version: '3.9'

services:
  db:
    image: postgres:13
    container_name: myproject-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - django-net

  web:
    build: .
    container_name: myproject-web
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django-net
      - general-net  # <--- Aquí agregamos la red de NPM
    expose:
      - "8000"

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  django-net:
    driver: bridge
  general-net:        # <--- Declaramos que es una red externa
    external: true
