services:
  db:
    image: postgres:13
    container_name: myproject-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - django-net

  web:
    build: .
    container_name: myproject-web
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django-net
    expose:
      - "8000"
