services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - django-net

  web:
    build: .
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - django-net
    expose:
      - "8000"   # Exponemos solo internamente, sin mapear puerto al host

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  django-net:
